version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: descomplica
    ports:
      - 3306:3306

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - './server:/server'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - './app:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
